### ISSUE TITLE
Bug: keydown:Enter is blocked by imagelightbox

### ISSUE THREAD

**Issue by Art4** [rejas/imagelightbox#133]
imagelightbox blocks the use of the Enter button.

### How to reproduce

1. Go to https://rejas.github.io/imagelightbox/ with your browser
2. Open the developer tools [F12]
3. Manipulate the DOM with creating a `textarea` tag after the container div, see the example below
4. Click inside the new textarea to focus it
5. Try to create a line break by using the Enter key on your keyboard.

**Code example:**
![bildschirmfoto vom 2017-09-24 17-08-30](https://user-images.githubusercontent.com/2162994/30783892-0a595ea4-a14b-11e7-88ed-e9e98ad283ec.png)

**It should look like this**
![imagelightbox](https://user-images.githubusercontent.com/2162994/30783881-dcf71a32-a14a-11e7-9e18-9dcf612d0032.png)

### What I expect

The Enter key should create a line break.

### What happens instead?

The Enter key creates no line break.

**Comment by Art4** [comment]
v0.7.1 don't have this bug. It was introduced somewhere between v0.7.1 and v0.7.5.

**Comment by rejas** [comment]
First: Best bug report I've seen in my life, well done!
Second: Confirmed, introduced via commit 36de2f0bcd1b7e904b26f8dbccc79577404608b6 in https://github.com/rejas/imagelightbox/pull/118 
Third: Maybe @paxperscientiam can say for what that culprit line 559 is needed?

**Comment by paxperscientiam** [comment]
Hello @rejas and @Art4 

Yes, this is a good observation. I had set enter to toggle fullscreen.

@Art4 , Is it "released" when you exit the lightbox?

@rejas , maybe a key combo would be a better idea?

**Comment by Art4** [comment]
> Is it "released" when you exit the lightbox?

@paxperscientiam No, I can open and close the fullscreen, but the Enter key has no effect.

**Comment by rejas** [comment]
@paxperscientiam what does the key do ?

**Comment by Art4** [comment]
What about a new button in the right bottom corner for the fullscreen mode instead of a key combo?

**Comment by paxperscientiam** [comment]
Its supposed to toggle fullscreen

Christopher

**Comment by paxperscientiam** [comment]
I like that. Iirc, @rejas did not like it. But that was long ago. Maybe
he's changed his mind

Christopher

Sent from my iPhone

On Sep 24, 2017 10:45 PM, "Artur Weigandt" <notifications@github.com> wrote:

What about a new button in the right bottom corner for the fullscreen mode
instead of a key combo?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rejas/imagelightbox/issues/133#issuecomment-331763840>,
or mute the thread

**Comment by rejas** [comment]
Will take a look at #129 seperatly :-)
As for this issue: I think the underlying bug is a that the key press is handled even when the imagelightbox is not opened. That also leads to strange behaviour when one navigates with the left/right keys. All those keypresses should only get handled when the lightbox is opened and present. Otherwise they get propagated to the document normally. Agree?

**Comment by Art4** [comment]
Agreed.

**Comment by rejas** [comment]
Release v0.8.0, hope it helps :-)
