### ISSUE TITLE
Some thoughts on further improvements

### ISSUE THREAD

**Issue by paxperscientiam** [rejas/imagelightbox#33]
Hey @rejas 

I don't think captions should fade away when switching from image to the next: it seems like an unnecessary distraction. If instead the caption box remained when changing over images, I think it would be better.

On the UX side of things, the ability to slide over to the next image via trackpad or mobile screen, would be great. Is this something you've thought about? If interested, I could probably lend a hand.

EDIT:
I forgot to mention another feature that I think would be pretty darn awesome. For large screens, particularly in portrait orientation, it could be very useful to have option to show two lightbox galleries simultaneously.

EDIT 2:
Deeplinking

**Comment by rejas** [comment]
Hey pax, thx for the input. My thoughts:
- fading captions: didnt notice it before, that was already in the original code. in my opinion the default look&feel should be as smooth as possible while allowing to modifgy it to your own needs as much as possible. so yes, probably the fade should go...
- sliding via touch/trackpad is a MUST (so much for testing my stuff on mobile ;-),  so your hand would be greatly appreciated here :-)
- interesting idea... so one gallery but two images of it at the same time? sounds more like a slider like https://kenwheeler.github.io/slick/ maybe out of scope here?
- deeplinking to image X so that the imagebox opens directly with it? nice idea too.

**Comment by paxperscientiam** [comment]
@rejas 
Hey, good to hear from you.

• I don't know much about project management WRT Github. Can you put the fading captions issue on a to-do list?
• To this end, I think we want a sliding motion to be equivalent to pressing left/right buttons, correct?
• Scope creep alert! Yeah, you are totally right. 
• I actually started tinkering with deeplinking and it's going well so far. I hope to put up a rough draft soon. You can expect something on this end.

**Comment by rejas** [comment]
Added new issues for all three feature enhancements you mentioned. That should be enough with regards to project managemnt here. If you have a pull request for any of this features, just mention the issue url in the commit and all should be fine I think. Thanks for the input.
